# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:

    assets:
        version: 'v1.0.0' # Change this version number to force refresh
        version_format: '%%s?version=%%s'

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
    http_client:
        default_options:
            verify_peer: false

parameters:
    recipe_images_directory: '%kernel.project_dir%/public/style/images/recipeImages'


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file


