<?php
// src/Controller/TastyTableController.php
// src/Controller/TastyTableController.php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Response;
//use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\User\UserInterface;

class TastyTableController extends AbstractController
{


    /**
     * @Route("/User", name="user")
     */

    public function show(UserRepository $userRepository, $id)
    {
        $user = $userRepository->find($id);

        if (!$user) {
            throw $this->createNotFoundException('No user found for id '.$id);
        }

        return $this->render('Pages/index.html.twig', [
            'user' => $user,
        ]);
    }



    #[Route('/',name:'logIn')]
    public function homePage(): Response
    {

        $tracks=[['name'=>'ramazan','surname'=>'yetismis'],
            ['name'=>'ramo','surname'=>'yetismis'],
            ['name'=>'ramazan','surname'=>'yetismis']

           ];
        return $this->render('Pages/index.html.twig',[
           'title'=> 'Ramazan and Ramo',
            'tracks'=>$tracks,
        ]);
    }

    #[Route(User::class)]
    public function getUser(): ?UserInterface
    {
        return parent::getUser(); // TODO: Change the autogenerated stub
    }


    #[Route('/register',name:'SignIn')]
    public function register(): Response
    {

        $tracks=[['name'=>'ramazan','surname'=>'yetismis'],
            ['name'=>'ramo','surname'=>'yetismis'],
            ['name'=>'ramazan','surname'=>'yetismis']

        ];
        return $this->render('Pages/register.html.twig',[
            'title'=> 'Ramazan and Ramo',
            'tracks'=>$tracks,
        ]);
    }

}

